-- ============================================================================
-- StudentOS — the quiz engine
--
-- XP used to measure activity: minutes on a timer, boxes ticked. Both are
-- farmable from the client, because both are written by the client. This
-- migration adds the first thing in the app that measures *knowledge*, and the
-- design follows from one rule: a student must never be able to write their
-- own score.
--
-- Three defences, in order of importance:
--
--   1. `quiz_attempts` and `quiz_answers` have a select policy and NO insert,
--      update or delete policy at all. RLS denies by default, so the only
--      writer is the service role — i.e. the `quiz-grade` Edge Function. This
--      is the same shape `subscriptions` already uses for webhook-written rows
--      (00003), and the house rule in docs/SECURITY.md.
--
--   2. `quiz_questions` has NO select policy either, so a student cannot read
--      `correct_index` out of PostgREST before answering. The runner reads
--      `quiz_questions_public`, a view with the answers projected away.
--
--   3. `xp_ledger` carries a unique key on (user_id, event, source_id), so an
--      award is idempotent. Replaying a grade request pays nothing the second
--      time, and `award_xp()` does the ledger insert and the profile update in
--      one statement each inside a single function — closing the read-modify-
--      write race in gamification-service, where two concurrent awards read the
--      same XP snapshot and one overwrites the other.
--
-- Idempotent.
-- ============================================================================

-- ── quizzes ─────────────────────────────────────────────────────────────────

create table if not exists public.quizzes (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references auth.users(id) on delete cascade,
  -- Keep the quiz when a module is deleted; it is still worth revising from.
  module_id      uuid references public.modules(id) on delete set null,
  title          text not null default 'Untitled quiz',
  -- ai   = generated by quiz-generate from note text
  -- note = generated on-device from a note (demo mode / no Gemini key)
  -- manual = the student wrote the questions
  source         text not null default 'manual' check (source in ('ai', 'note', 'manual')),
  -- boss = the end-of-module test; worth more XP, shown differently
  kind           text not null default 'practice' check (kind in ('practice', 'boss')),
  question_count integer not null default 0 check (question_count >= 0),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists quizzes_user_id_idx on public.quizzes (user_id);
create index if not exists quizzes_module_id_idx on public.quizzes (module_id);

-- ── quiz_questions ──────────────────────────────────────────────────────────

create table if not exists public.quiz_questions (
  id            uuid primary key default gen_random_uuid(),
  quiz_id       uuid not null references public.quizzes(id) on delete cascade,
  -- Not named "position": that is a SQL function name, and the column then
  -- needs quoting in places it is easy to forget.
  ordinal       integer not null default 0,
  prompt        text not null,
  -- string[] of answer choices, indexed by correct_index.
  options       jsonb not null default '[]'::jsonb,
  correct_index integer not null default 0 check (correct_index >= 0),
  explanation   text,
  created_at    timestamptz not null default now()
);

create index if not exists quiz_questions_quiz_id_idx on public.quiz_questions (quiz_id, ordinal);

-- ── quiz_attempts ───────────────────────────────────────────────────────────

create table if not exists public.quiz_attempts (
  id               uuid primary key default gen_random_uuid(),
  user_id          uuid not null references auth.users(id) on delete cascade,
  quiz_id          uuid not null references public.quizzes(id) on delete cascade,
  score            integer not null default 0 check (score >= 0),
  total            integer not null default 0 check (total >= 0),
  -- Client-reported and advisory only: it is displayed, never used to decide
  -- XP, precisely because the client controls it.
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  xp_awarded       integer not null default 0 check (xp_awarded >= 0),
  submitted_at     timestamptz not null default now(),
  created_at       timestamptz not null default now()
);

create index if not exists quiz_attempts_user_id_idx on public.quiz_attempts (user_id, submitted_at desc);
create index if not exists quiz_attempts_quiz_id_idx on public.quiz_attempts (quiz_id);

-- ── quiz_answers ────────────────────────────────────────────────────────────

create table if not exists public.quiz_answers (
  id           uuid primary key default gen_random_uuid(),
  attempt_id   uuid not null references public.quiz_attempts(id) on delete cascade,
  question_id  uuid not null references public.quiz_questions(id) on delete cascade,
  -- Null means the question was left unanswered.
  chosen_index integer check (chosen_index >= 0),
  correct      boolean not null default false,
  created_at   timestamptz not null default now()
);

create index if not exists quiz_answers_attempt_id_idx on public.quiz_answers (attempt_id);

-- ── xp_ledger ───────────────────────────────────────────────────────────────

create table if not exists public.xp_ledger (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users(id) on delete cascade,
  -- 'quiz_completed', 'quest_claimed', … — matches the XpEvent union in TS.
  event      text not null,
  -- What earned it. For a quiz this is the quiz id, NOT the attempt id: the
  -- first pass at a quiz pays, later ones do not. Re-attempting for revision
  -- still records a score; it just cannot be farmed.
  source_id  text not null,
  amount     integer not null check (amount >= 0),
  created_at timestamptz not null default now(),
  unique (user_id, event, source_id)
);

create index if not exists xp_ledger_user_id_idx on public.xp_ledger (user_id, created_at desc);

-- ── updated_at: 00002 attaches this by scanning the tables that existed then,
--    so a table added later has to opt in explicitly ─────────────────────────

drop trigger if exists set_updated_at on public.quizzes;
create trigger set_updated_at before update on public.quizzes
  for each row execute function public.set_updated_at();

-- ── RLS ─────────────────────────────────────────────────────────────────────

alter table public.quizzes enable row level security;
alter table public.quiz_questions enable row level security;
alter table public.quiz_attempts enable row level security;
alter table public.quiz_answers enable row level security;
alter table public.xp_ledger enable row level security;

-- quizzes: ordinary owner-only CRUD.
drop policy if exists "quizzes_select_own" on public.quizzes;
create policy "quizzes_select_own" on public.quizzes
  for select using (auth.uid() = user_id);

drop policy if exists "quizzes_insert_own" on public.quizzes;
create policy "quizzes_insert_own" on public.quizzes
  for insert with check (auth.uid() = user_id);

drop policy if exists "quizzes_update_own" on public.quizzes;
create policy "quizzes_update_own" on public.quizzes
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "quizzes_delete_own" on public.quizzes;
create policy "quizzes_delete_own" on public.quizzes
  for delete using (auth.uid() = user_id);

-- quiz_questions: writable by the owner, and deliberately NOT readable.
--
-- No select policy, so `select *` returns nothing over PostgREST and the answer
-- key cannot be fetched before answering. Writes are allowed because a student
-- may author their own quiz — knowing the answers to questions you wrote
-- yourself is not a leak, and grading still happens server-side either way.
-- A client insert must not ask for the row back (`Prefer: return=minimal`),
-- because RETURNING needs select permission; see `insertMany` in db.ts.
drop policy if exists "quiz_questions_insert_own" on public.quiz_questions;
create policy "quiz_questions_insert_own" on public.quiz_questions
  for insert with check (
    exists (select 1 from public.quizzes q where q.id = quiz_id and q.user_id = auth.uid())
  );

drop policy if exists "quiz_questions_update_own" on public.quiz_questions;
create policy "quiz_questions_update_own" on public.quiz_questions
  for update using (
    exists (select 1 from public.quizzes q where q.id = quiz_id and q.user_id = auth.uid())
  );

drop policy if exists "quiz_questions_delete_own" on public.quiz_questions;
create policy "quiz_questions_delete_own" on public.quiz_questions
  for delete using (
    exists (select 1 from public.quizzes q where q.id = quiz_id and q.user_id = auth.uid())
  );

-- quiz_attempts / quiz_answers / xp_ledger: read-only to the owner.
-- No insert, update or delete policy anywhere — the service role writes these,
-- and RLS denies everything it has no policy for. This is the security
-- assertion of the whole feature; a test in the suite asserts it stays true.
drop policy if exists "quiz_attempts_select_own" on public.quiz_attempts;
create policy "quiz_attempts_select_own" on public.quiz_attempts
  for select using (auth.uid() = user_id);

drop policy if exists "quiz_answers_select_own" on public.quiz_answers;
create policy "quiz_answers_select_own" on public.quiz_answers
  for select using (
    exists (
      select 1 from public.quiz_attempts a
       where a.id = attempt_id and a.user_id = auth.uid()
    )
  );

drop policy if exists "xp_ledger_select_own" on public.xp_ledger;
create policy "xp_ledger_select_own" on public.xp_ledger
  for select using (auth.uid() = user_id);

-- ── The runner's view of a question ─────────────────────────────────────────
--
-- `security_invoker = false` (the default, stated here because it is the point
-- rather than an oversight): the view runs as its owner and so can read a table
-- the caller cannot. That is exactly what projects the answers away — and it is
-- why the view must do its own ownership check, which the WHERE clause below
-- is. Supabase's advisor flags definer views generically; this one is
-- deliberate and is the mechanism, not a mistake.
drop view if exists public.quiz_questions_public;
create view public.quiz_questions_public
with (security_invoker = false) as
  select
    q.id,
    q.quiz_id,
    q.ordinal,
    q.prompt,
    q.options,
    q.created_at
  from public.quiz_questions q
  join public.quizzes z on z.id = q.quiz_id
  where z.user_id = auth.uid();

grant select on public.quiz_questions_public to authenticated;

-- ── award_xp: the one way XP is granted ─────────────────────────────────────

create or replace function public.award_xp(
  p_user_id   uuid,
  p_event     text,
  p_source_id text,
  p_amount    integer
)
returns table (awarded integer, total_xp integer, new_level integer)
language plpgsql
-- SECURITY DEFINER so it can write the ledger and the profile regardless of the
-- caller's policies; the pinned search_path stops the usual hijack.
security definer
set search_path = public, pg_temp
as $$
declare
  v_amount   integer := greatest(0, coalesce(p_amount, 0));
  v_inserted boolean := false;
  v_xp       integer;
  v_level    integer;
begin
  -- The unique key is what makes this idempotent: a replayed grade, a
  -- double-clicked claim or a retried request all land here and do nothing.
  insert into public.xp_ledger (user_id, event, source_id, amount)
  values (p_user_id, p_event, p_source_id, v_amount)
  on conflict (user_id, event, source_id) do nothing;
  v_inserted := found;

  if v_inserted then
    -- One statement, so the read and the write cannot be separated by another
    -- award. Every `xp` on the right-hand side is the pre-update value, which
    -- keeps the two assignments consistent with each other.
    -- Level curve mirrors levelForXp() in gamification-service.ts exactly:
    -- floor(sqrt(xp / 100)) + 1.
    update public.profiles
       set xp    = xp + v_amount,
           level = floor(sqrt((xp + v_amount) / 100.0)) + 1
     where id = p_user_id
     returning xp, level into v_xp, v_level;
  else
    select p.xp, p.level into v_xp, v_level from public.profiles p where p.id = p_user_id;
  end if;

  return query select
    case when v_inserted then v_amount else 0 end,
    coalesce(v_xp, 0),
    coalesce(v_level, 1);
end;
$$;

-- Callable only by the service role. A student who could call this directly
-- would choose their own amount, which is the entire thing being prevented.
revoke all on function public.award_xp(uuid, text, text, integer) from public;
revoke all on function public.award_xp(uuid, text, text, integer) from anon;
revoke all on function public.award_xp(uuid, text, text, integer) from authenticated;

-- ── Catalogue clean-up from the same release ────────────────────────────────
--
-- The seeds in 00002 are `on conflict do nothing`, so they only ever apply to a
-- fresh database. These three changes have to be stated again here or an
-- existing project keeps the old rows forever.

-- The AI Coach became AI quiz generation. Same entitlement, repointed, so a Pro
-- subscriber who paid for "AI" still has one.
update public.feature_flags
   set key = 'ai_quiz',
       description = 'AI-generated quizzes from notes'
 where key = 'ai_coach'
   and not exists (select 1 from public.feature_flags f where f.key = 'ai_quiz');

-- Budget is gone, and this badge was seeded but never awarded by any code path,
-- so nothing can reference it. Guarded anyway rather than assuming.
delete from public.badges
 where id = 'budget-boss'
   and not exists (select 1 from public.achievements a where a.badge_id = 'budget-boss');

-- ── Realtime: a graded attempt should appear without a refresh ──────────────

do $$
declare
  t text;
begin
  foreach t in array array['quizzes', 'quiz_attempts', 'xp_ledger']
  loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;

    execute format('alter table public.%I replica identity full', t);
  end loop;
end;
$$;
